// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rtvnaloga.Data;

#nullable disable

namespace rtvnaloga.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250107081220_AdditionalData")]
    partial class AdditionalData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rtvnaloga.Models.AccountHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountHeaders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = 0,
                            DateTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 77553344,
                            RecipientAddress = "Makadamska cesta 2",
                            RecipientLocation = "1000 Ljubljana",
                            RecipientName = "Janez Novak"
                        },
                        new
                        {
                            Id = 2,
                            Currency = 0,
                            DateTime = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 1234567,
                            RecipientAddress = "Asfaltna cesta 3",
                            RecipientLocation = "1231 Crnuce",
                            RecipientName = "Marija Novak"
                        },
                        new
                        {
                            Id = 3,
                            Currency = 0,
                            DateTime = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 987654,
                            RecipientAddress = "Testna ulica 12",
                            RecipientLocation = "3000 Celje",
                            RecipientName = "Marko Horvat"
                        },
                        new
                        {
                            Id = 4,
                            Currency = 0,
                            DateTime = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 99887766,
                            RecipientAddress = "Ulica Miru 10",
                            RecipientLocation = "2000 Maribor",
                            RecipientName = "Ana Kranjc"
                        },
                        new
                        {
                            Id = 5,
                            Currency = 1,
                            DateTime = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 11122233,
                            RecipientAddress = "Bukova pot 4",
                            RecipientLocation = "4000 Kranj",
                            RecipientName = "Petra Zagar"
                        },
                        new
                        {
                            Id = 6,
                            Currency = 0,
                            DateTime = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 44455566,
                            RecipientAddress = "Glavna cesta 1",
                            RecipientLocation = "6000 Koper",
                            RecipientName = "Tomaž Vidmar"
                        },
                        new
                        {
                            Id = 7,
                            Currency = 0,
                            DateTime = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 12340001,
                            RecipientAddress = "Obala 77",
                            RecipientLocation = "6320 Portorož",
                            RecipientName = "Nina Tomšič"
                        },
                        new
                        {
                            Id = 8,
                            Currency = 1,
                            DateTime = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 55599911,
                            RecipientAddress = "Trg Svobode 9",
                            RecipientLocation = "5000 Nova Gorica",
                            RecipientName = "Goran Kovač"
                        },
                        new
                        {
                            Id = 9,
                            Currency = 0,
                            DateTime = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 88776655,
                            RecipientAddress = "Jablana cesta 6",
                            RecipientLocation = "8000 Novo Mesto",
                            RecipientName = "Maja Breznik"
                        },
                        new
                        {
                            Id = 10,
                            Currency = 0,
                            DateTime = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 22334455,
                            RecipientAddress = "Zgornja pot 22",
                            RecipientLocation = "9000 Murska Sobota",
                            RecipientName = "Luka Zagorc"
                        },
                        new
                        {
                            Id = 11,
                            Currency = 0,
                            DateTime = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 33445566,
                            RecipientAddress = "Sončna ulica 5",
                            RecipientLocation = "8001 Novo Mesto",
                            RecipientName = "Sara Kavčič"
                        },
                        new
                        {
                            Id = 12,
                            Currency = 0,
                            DateTime = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 69696969,
                            RecipientAddress = "Cankarjeva cesta 10",
                            RecipientLocation = "2101 Maribor",
                            RecipientName = "Domen Potrč"
                        },
                        new
                        {
                            Id = 13,
                            Currency = 0,
                            DateTime = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 20247777,
                            RecipientAddress = "Lipova pot 16",
                            RecipientLocation = "3210 Slovenske Konjice",
                            RecipientName = "Eva Mlakar"
                        });
                });

            modelBuilder.Entity("rtvnaloga.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountHeaderId")
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AccountHeaderId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountHeaderId = 1,
                            Amount = 12.75f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 2,
                            AccountHeaderId = 1,
                            Amount = 3.77f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 3,
                            AccountHeaderId = 1,
                            Amount = 12.75f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 4,
                            AccountHeaderId = 1,
                            Amount = 3.77f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 5,
                            AccountHeaderId = 2,
                            Amount = 8.12f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 6,
                            AccountHeaderId = 2,
                            Amount = 5.17f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 7,
                            AccountHeaderId = 2,
                            Amount = 24.77f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 8,
                            AccountHeaderId = 3,
                            Amount = 6f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 9,
                            AccountHeaderId = 3,
                            Amount = 18.5f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 10,
                            AccountHeaderId = 3,
                            Amount = 1.8f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 11,
                            AccountHeaderId = 3,
                            Amount = 14.4f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 12,
                            AccountHeaderId = 3,
                            Amount = 30f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 13,
                            AccountHeaderId = 4,
                            Amount = 4.5f,
                            ItemName = "TV - Zasebna raba - pavšal",
                            Price = 8f
                        },
                        new
                        {
                            Id = 14,
                            AccountHeaderId = 4,
                            Amount = 12.7f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 15,
                            AccountHeaderId = 4,
                            Amount = 2f,
                            ItemName = "Internet - Pravne osebe",
                            Price = 25f
                        },
                        new
                        {
                            Id = 16,
                            AccountHeaderId = 5,
                            Amount = 1.2f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 17,
                            AccountHeaderId = 5,
                            Amount = 3.5f,
                            ItemName = "RA - Zasebna raba - pavšal",
                            Price = 8f
                        },
                        new
                        {
                            Id = 18,
                            AccountHeaderId = 5,
                            Amount = 2f,
                            ItemName = "Digitalni paket - Pravne osebe",
                            Price = 15f
                        },
                        new
                        {
                            Id = 19,
                            AccountHeaderId = 6,
                            Amount = 10f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 20,
                            AccountHeaderId = 6,
                            Amount = 2.5f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 9f
                        },
                        new
                        {
                            Id = 21,
                            AccountHeaderId = 6,
                            Amount = 1f,
                            ItemName = "Mobilni paket - Pravne osebe",
                            Price = 20f
                        },
                        new
                        {
                            Id = 22,
                            AccountHeaderId = 7,
                            Amount = 5f,
                            ItemName = "TV - Zasebna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 23,
                            AccountHeaderId = 7,
                            Amount = 7.2f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 24,
                            AccountHeaderId = 7,
                            Amount = 3f,
                            ItemName = "IP Telefonija - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 25,
                            AccountHeaderId = 8,
                            Amount = 2.2f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 26,
                            AccountHeaderId = 8,
                            Amount = 5f,
                            ItemName = "RA - Zasebna raba - pavšal",
                            Price = 5f
                        },
                        new
                        {
                            Id = 27,
                            AccountHeaderId = 8,
                            Amount = 4.5f,
                            ItemName = "Digitalni paket - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 28,
                            AccountHeaderId = 9,
                            Amount = 8.7f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 29,
                            AccountHeaderId = 9,
                            Amount = 3.4f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 30,
                            AccountHeaderId = 9,
                            Amount = 1.5f,
                            ItemName = "Mobilni paket - Pravne osebe",
                            Price = 18f
                        },
                        new
                        {
                            Id = 31,
                            AccountHeaderId = 10,
                            Amount = 4f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 8f
                        },
                        new
                        {
                            Id = 32,
                            AccountHeaderId = 10,
                            Amount = 9.2f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 33,
                            AccountHeaderId = 10,
                            Amount = 6f,
                            ItemName = "Internet - Pravne osebe",
                            Price = 12f
                        },
                        new
                        {
                            Id = 34,
                            AccountHeaderId = 11,
                            Amount = 2.3f,
                            ItemName = "TV - Zasebna raba - pavšal",
                            Price = 5f
                        },
                        new
                        {
                            Id = 35,
                            AccountHeaderId = 11,
                            Amount = 6.8f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 36,
                            AccountHeaderId = 11,
                            Amount = 2.2f,
                            ItemName = "IP Telefonija - Pravne osebe",
                            Price = 15f
                        },
                        new
                        {
                            Id = 37,
                            AccountHeaderId = 12,
                            Amount = 2.5f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 38,
                            AccountHeaderId = 12,
                            Amount = 8f,
                            ItemName = "RA - Zasebna raba - pavšal",
                            Price = 5f
                        },
                        new
                        {
                            Id = 39,
                            AccountHeaderId = 12,
                            Amount = 1.6f,
                            ItemName = "Mobilni paket - Pravne osebe",
                            Price = 20f
                        },
                        new
                        {
                            Id = 40,
                            AccountHeaderId = 13,
                            Amount = 3.3f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 8f
                        },
                        new
                        {
                            Id = 41,
                            AccountHeaderId = 13,
                            Amount = 11.1f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 42,
                            AccountHeaderId = 13,
                            Amount = 5f,
                            ItemName = "Internet - Pravne osebe",
                            Price = 14f
                        });
                });

            modelBuilder.Entity("rtvnaloga.Models.InvoiceItem", b =>
                {
                    b.HasOne("rtvnaloga.Models.AccountHeader", "AccountHeader")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("AccountHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountHeader");
                });

            modelBuilder.Entity("rtvnaloga.Models.AccountHeader", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
