// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rtvnaloga.Data;

#nullable disable

namespace rtvnaloga.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250103133836_SeedTestData")]
    partial class SeedTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rtvnaloga.Models.AccountHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountHeaders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = 0,
                            DateTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 77553344,
                            RecipientAddress = "Makadamska cesta 2",
                            RecipientLocation = "1000 Ljubljana",
                            RecipientName = "Janez Novak"
                        },
                        new
                        {
                            Id = 2,
                            Currency = 0,
                            DateTime = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 1234567,
                            RecipientAddress = "Asfaltna cesta 3",
                            RecipientLocation = "1231 Crnuce",
                            RecipientName = "Marija Novak"
                        },
                        new
                        {
                            Id = 3,
                            Currency = 0,
                            DateTime = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 987654,
                            RecipientAddress = "Testna ulica 12",
                            RecipientLocation = "3000 Celje",
                            RecipientName = "Marko Horvat"
                        });
                });

            modelBuilder.Entity("rtvnaloga.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountHeaderId")
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AccountHeaderId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountHeaderId = 1,
                            Amount = 12.75f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 2,
                            AccountHeaderId = 1,
                            Amount = 3.77f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 3,
                            AccountHeaderId = 1,
                            Amount = 12.75f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 4,
                            AccountHeaderId = 1,
                            Amount = 3.77f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 5,
                            AccountHeaderId = 2,
                            Amount = 8.12f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 6,
                            AccountHeaderId = 2,
                            Amount = 5.17f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 7,
                            AccountHeaderId = 2,
                            Amount = 24.77f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 8,
                            AccountHeaderId = 3,
                            Amount = 6f,
                            ItemName = "TV - Javna raba - pavšal",
                            Price = 4f
                        },
                        new
                        {
                            Id = 9,
                            AccountHeaderId = 3,
                            Amount = 18.5f,
                            ItemName = "RA - Javna raba - pavšal",
                            Price = 20f
                        },
                        new
                        {
                            Id = 10,
                            AccountHeaderId = 3,
                            Amount = 1.8f,
                            ItemName = "TV - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 11,
                            AccountHeaderId = 3,
                            Amount = 14.4f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        },
                        new
                        {
                            Id = 12,
                            AccountHeaderId = 3,
                            Amount = 30f,
                            ItemName = "RA - Zasebna raba - Pravne osebe",
                            Price = 10f
                        });
                });

            modelBuilder.Entity("rtvnaloga.Models.InvoiceItem", b =>
                {
                    b.HasOne("rtvnaloga.Models.AccountHeader", "AccountHeader")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("AccountHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountHeader");
                });

            modelBuilder.Entity("rtvnaloga.Models.AccountHeader", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
